version: 2
updates:
  # Frontend app (deployed on AWS)
  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: daily
    labels: [dependencies, javascript, aws, frontend]

  # Backend app (deployed on Azure)
  - package-ecosystem: "npm"
    directory: "/app/backend"
    schedule:
      interval: daily

  # Terraform – AWS
  - package-ecosystem: "terraform"
    directory: "/infra/aws"
    schedule:
      interval: daily
    labels: [aws]

  # Terraform – Azure
  - package-ecosystem: "terraform"
    directory: "/infra/azure"
    schedule:
      interval: daily

  # Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
