name: 'Azure Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/azure/**'
      - 'app/backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'infra/azure/**'
      - 'app/backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  azure-terraform:
    name: 'Azure Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_tg_api_key: ${{ secrets.TWINGATE_API_KEY }}
      TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      TF_VAR_doppler_token: ${{ secrets.DOPPLER_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: infra/azure

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to Azure
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false --out out.tfplan

    # Set up OPA
    - name: Set up OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/v1.0.0/opa_linux_amd64_static
        chmod +x opa
        sudo mv opa /usr/local/bin/
      
    # Run OPA
    - name: Run Conversion
      run: terraform show -json out.tfplan > out.tfplan.json
        
    # Run OPA
    - name: Run Policy Check
      run: opa exec --bundle=../policies/ --decision main/tag_policy_violations --fail-non-empty out.tfplan.json

      # Only on push to "main", change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform apply -auto-approve -input=false
